### ISSUE TITLE
Can't build SolidOak because of some error with Gtk

### ISSUE THREAD

**Issue by vi** [rust-gnome/gtk#83]
```
Build failed, waiting for other jobs to finish...

failed to run custom build command for `gtk-sys v0.1.0 (https://github.com/oakes/gtk#b9b3d2bc)`
Process didn't exit successfully: `/home/vi/home/rust/SolidOak/target/debug/build/gtk-sys-4fc3492795cbacc8/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=native=/usr/lib/i386-linux-gnu
cargo:rustc-link-lib=gtk-3
cargo:rustc-link-lib=gdk-3
cargo:rustc-link-lib=atk-1.0
cargo:rustc-link-lib=gio-2.0
cargo:rustc-link-lib=pangocairo-1.0
cargo:rustc-link-lib=gdk_pixbuf-2.0
cargo:rustc-link-lib=cairo-gobject
cargo:rustc-link-lib=pango-1.0
cargo:rustc-link-lib=cairo
cargo:rustc-link-lib=gobject-2.0
cargo:rustc-link-lib=glib-2.0
cargo:rustc-link-search=native=/usr/lib/i386-linux-gnu
cargo:rustc-link-search=native=/usr/lib
cargo:rustc-link-lib=vte2_90
cargo:rustc-link-lib=gtk-3
cargo:rustc-link-lib=gdk-3
cargo:rustc-link-lib=atk-1.0
cargo:rustc-link-lib=pangocairo-1.0
cargo:rustc-link-lib=gdk_pixbuf-2.0
cargo:rustc-link-lib=cairo-gobject
cargo:rustc-link-lib=pango-1.0
cargo:rustc-link-lib=gio-2.0
cargo:rustc-link-lib=gobject-2.0
cargo:rustc-link-lib=glib-2.0
cargo:rustc-link-lib=cairo
cargo:rustc-link-lib=X11
TARGET = Some("i686-unknown-linux-gnu")
CARGO_MANIFEST_DIR = Some("/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys")
OUT_DIR = Some("/home/vi/home/rust/SolidOak/target/debug/build/gtk-sys-4fc3492795cbacc8/out")
TARGET = Some("i686-unknown-linux-gnu")
OPT_LEVEL = Some("0")
PROFILE = Some("debug")
debug 0
TARGET = Some("i686-unknown-linux-gnu")
HOST = Some("i686-unknown-linux-gnu")
CC_i686-unknown-linux-gnu = None
CC_i686_unknown_linux_gnu = None
HOST_CC = None
CC = None
TARGET = Some("i686-unknown-linux-gnu")
HOST = Some("i686-unknown-linux-gnu")
CFLAGS_i686-unknown-linux-gnu = None
CFLAGS_i686_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
TARGET = Some("i686-unknown-linux-gnu")
HOST = Some("i686-unknown-linux-gnu")
CC_i686-unknown-linux-gnu = None
CC_i686_unknown_linux_gnu = None
HOST_CC = None
CC = None
running: "cc" "-O0" "-c" "-ffunction-sections" "-fdata-sections" "-m32" "-I" "/usr/include/gtk-3.0" "-I" "/usr/include/pango-1.0" "-I" "/usr/include/gio-unix-2.0/" "-I" "/usr/include/atk-1.0" "-I" "/usr/include/cairo" "-I" "/usr/include/gdk-pixbuf-2.0" "-I" "/usr/include/freetype2" "-I" "/usr/include/glib-2.0" "-I" "/usr/lib/i386-linux-gnu/glib-2.0/include" "-I" "/usr/include/pixman-1" "-I" "/usr/include/libpng12" "-DGTK_3_6" "-DGTK_3_4" "-DGTK_3_8" "-DGTK_3_10" "/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c" "-o" "/home/vi/home/rust/SolidOak/target/debug/build/gtk-sys-4fc3492795cbacc8/out/src/gtk_glue.o"


command did not execute successfully, got: exit code: 1



--- stderr
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c:404:1: error: unknown type name ‘GtkLevelBar’
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c: In function ‘cast_GtkLevelBar’:
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c:405:5: warning: return makes pointer from integer without a cast [enabled by default]
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c: At top level:
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c:459:1: error: unknown type name ‘GtkMenuButton’
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c: In function ‘cast_GtkMenuButton’:
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c:460:5: warning: return makes pointer from integer without a cast [enabled by default]
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c: At top level:
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c:467:1: error: unknown type name ‘GtkSearchBar’
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c: In function ‘cast_GtkSearchBar’:
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c:468:5: warning: return makes pointer from integer without a cast [enabled by default]
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c: At top level:
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c:471:1: error: unknown type name ‘GtkStack’
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c: In function ‘cast_GtkStack’:
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c:472:5: warning: return makes pointer from integer without a cast [enabled by default]
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c: At top level:
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c:475:1: error: unknown type name ‘GtkStackSwitcher’
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c: In function ‘cast_GtkStackSwitcher’:
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c:476:5: warning: return makes pointer from integer without a cast [enabled by default]
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c: At top level:
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c:479:1: error: unknown type name ‘GtkRevealer’
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c: In function ‘cast_GtkRevealer’:
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c:480:5: warning: return makes pointer from integer without a cast [enabled by default]
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c: At top level:
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c:483:1: error: unknown type name ‘GtkHeaderBar’
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c: In function ‘cast_GtkHeaderBar’:
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c:484:5: warning: return makes pointer from integer without a cast [enabled by default]
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c: At top level:
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c:487:1: error: unknown type name ‘GtkListBox’
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c: In function ‘cast_GtkListBox’:
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c:488:5: warning: return makes pointer from integer without a cast [enabled by default]
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c: At top level:
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c:491:1: error: unknown type name ‘GtkListBoxRow’
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c: In function ‘cast_GtkListBoxRow’:
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c:492:5: warning: return makes pointer from integer without a cast [enabled by default]
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c: At top level:
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c:495:1: error: unknown type name ‘GtkPlacesSidebar’
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c: In function ‘cast_GtkPlacesSidebar’:
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c:496:5: warning: return makes pointer from integer without a cast [enabled by default]
thread '<main>' panicked at 'explicit panic', /home/vi/home/rust/.cargo/registry/src/github.com-1285ae84e5963aae/gcc-0.3.5/src/lib.rs:384
```

Can it be caused by too stable libgtk-3-dev version (3.4.2-7) from Debian Wheezy? Does the project check system dependencies' versions before trying to compile itself?

**Comment by vi** [comment]
Changing to `features = ["gtk_3_4"]` in `Cargo.toml` made it fail with fewer error lines:

```
running: "cc" "-O0" "-c" "-ffunction-sections" "-fdata-sections" "-m32" "-I" "/usr/include/gtk-3.0" "-I" "/usr/include/pango-1.0" "-I" "/usr/include/gio-unix-2.0/" "-I" "/usr/include/atk-1.0" "-I" "/usr/include/cairo" "-I" "/usr/include/gdk-pixbuf-2.0" "-I" "/usr/include/freetype2" "-I" "/usr/include/glib-2.0" "-I" "/usr/lib/i386-linux-gnu/glib-2.0/include" "-I" "/usr/include/pixman-1" "-I" "/usr/include/libpng12" "-DGTK_3_4" "-DGTK_3_6" "/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c" "-o" "/home/vi/home/rust/SolidOak/target/debug/build/gtk-sys-4fc3492795cbacc8/out/src/gtk_glue.o"


command did not execute successfully, got: exit code: 1



--- stderr
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c:404:1: error: unknown type name ‘GtkLevelBar’
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c: In function ‘cast_GtkLevelBar’:
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c:405:5: warning: return makes pointer from integer without a cast [enabled by default]
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c: At top level:
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c:459:1: error: unknown type name ‘GtkMenuButton’
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c: In function ‘cast_GtkMenuButton’:
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c:460:5: warning: return makes pointer from integer without a cast [enabled by default]
thread '<main>' panicked at 'explicit panic', /home/vi/home/rust/.cargo/registry/src/github.com-1285ae84e5963aae/gcc-0.3.5/src/lib.rs:384
```

**Comment by vi** [comment]
After manual removal of the offending elements from `gtk_glue.c` the compilation got though.

**Comment by gkoz** [comment]
`SolidOak` [is requesting](https://github.com/oakes/SolidOak/blob/master/Cargo.toml#L16) GTK 3.10 support from the library. Naturally it won't build with older libs.

**Comment by vi** [comment]
Yes, but this dependency fails to build even if I change it to 3.4.

**Comment by GuillaumeGomez** [comment]
@vi: yes, that's because `SolidOak` needs features from the 3.10 version.

**Comment by vi** [comment]
I expect if I change 3_10 to 3_4 in Cargo.toml then the rust-gtk should build successfully, but SolidOak itself will fail to find something (in my case it's GtkStack). But changing from 3_10 to 3_4 only reduces number of compilation errors in rust-gtk, not completely removes.

**Comment by GuillaumeGomez** [comment]
It __should__ fail. (unless I'm wrong about this ?)

**Comment by gkoz** [comment]
3.6 is special, it's enabled by default, so you need to forgo the default option like this:
```
[dependencies.gtk]
features = ["gtk_3_4"]
default-features = false

**Comment by vi** [comment]
Without `default-features = false` line I get errors about `GtkLevelBar` and `GtkMenuButton`. With `default-features = false` I only get error about `GtkLevelBar`.

**Comment by gkoz** [comment]
> With default-features = false I only get error about GtkLevelBar.

This one we should fix.

**Comment by gkoz** [comment]
@vi could you test this patch?
```
--- a/gtk-sys/src/gtk_glue.c
+++ b/gtk-sys/src/gtk_glue.c
@@ -401,9 +401,11 @@ GtkAppChooserDialog* cast_GtkAppChooserDialog(GtkWidget* widget) {
     return GTK_APP_CHOOSER_DIALOG(widget);
 }
 
+#if defined(GTK_3_6)
 GtkLevelBar* cast_GtkLevelBar(GtkWidget* widget) {
     return GTK_LEVEL_BAR(widget);
 }
+#endif
 
 GtkFontChooserDialog* cast_GtkFontChooserDialog(GtkWidget* widget) {
     return GTK_FONT_CHOOSER_DIALOG(widget);
```

**Comment by vi** [comment]
Yes, editing `$HOME/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/gtk-sys/src/gtk_glue.c` this way fixed the compilation with `features = ["gtk_3_4"] default-features = false`.

Can't default-features automatically set to fase when target GTK version is 3.4?

**Comment by gkoz** [comment]
I don't think that's possible.

**Comment by gkoz** [comment]
@vi 
The patch has been merged so building with appropriate features should work.

**Comment by GuillaumeGomez** [comment]
@vi: so ?

**Comment by vi** [comment]
I abandoned attempts to build SolidOak against GTK 3.4 and made NixOS-dependent SolidOak depending on GTK 3.12 (which still does not work well, but the problem is unrelated).
